### ISSUE TITLE
dependency on tasty_backend profile

### ISSUE THREAD

**Issue by frederickjh** [jenitehan/tasty_backend_standard#2]
Hi Jeni! 
I saw you presentation in Amsterdam. I saw in the [README.md](https://github.com/jenitehan/tasty_backend_base/blob/master/Readme.md) for the tasty_backend_base that it says: 

> The Tasty Backend modules do **not** require you to use the Tasty Backend Install Profile. You can try it out on a new install someday.

However when I try to install the tasty_backend_standard I get the error message: 

> No release history was found for the requested project (tasty_backend).                                                                                           [error]
> Module tasty_backend_standard cannot be enabled because it depends on the following modules which could not be found: tasty_backend                               [error]

In the .info file I see the dependency on tasty_backend. Is this still a dependency?

Thanks!
Frederick

**Comment by frederickjh** [comment]
When I comment out the dependency in the .info file line 50 of [tasty_backend_standard.install](https://github.com/jenitehan/tasty_backend_standard/blob/master/tasty_backend_standard.install) seem to be causing the following error:

> $ drush -y en tasty_backend_standard 
> The following extensions will be enabled: tasty_backend_standard
> Do you really want to continue? (y/n): y
> Creating default object from empty value tasty_backend_standard.install:50                                                                                        [warning]
> exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'identifier'' in                          [error]
> /var/www/includes/database/database.inc:2171
> Stack trace:
> #0 /var/www/includes/database/database.inc(2171): PDOStatement->execute(Array)
> #1 /var/www/includes/database/database.inc(683): DatabaseStatementBase->execute(Array, Array)
> #2 /var/www/includes/database/mysql/query.inc(36): DatabaseConnection->query('INSERT INTO {fi...', Array, Array)
> #3 /var/www/includes/common.inc(7334): InsertQuery_mysql->execute()
> #4 /var/www/sites/all/modules/field_group/field_group.module(1880): drupal_write_record('field_group', Object(stdClass), Array)
> #5 /var/www/sites/all/modules/ctools/includes/export.inc(172): field_group_group_save(Object(stdClass))
> #6 /var/www/sites/all/modules/tasty_backend/tasty_backend_standard/tasty_backend_standard.install(56): ctools_export_crud_save('field_group', Object(stdClass))
> #7 [internal function]: tasty_backend_standard_install()
> #8 /var/www/includes/module.inc(922): call_user_func_array('tasty_backend_s...', Array)
> #9 /var/www/includes/module.inc(490): module_invoke('tasty_backend_s...', 'install')
> #10 /root/.composer/vendor/drush/drush/commands/core/drupal/environment_7.inc(143): module_enable(Array)
> #11 /root/.composer/vendor/drush/drush/commands/pm/pm.drush.inc(1122): drush_module_enable(Array)
> #12 [internal function]: drush_pm_enable('tasty_backend_s...')
> #13 /root/.composer/vendor/drush/drush/includes/command.inc(361): call_user_func_array('drush_pm_enable', Array)
> #14 /root/.composer/vendor/drush/drush/includes/command.inc(212): _drush_invoke_hooks(Array, Array)
> #15 [internal function]: drush_command('tasty_backend_s...')
> #16 /root/.composer/vendor/drush/drush/includes/command.inc(180): call_user_func_array('drush_command', Array)
> #17 /root/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(64): drush_dispatch(Array)
> #18 /root/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
> #19 /root/.composer/vendor/drush/drush/drush.php(11): drush_main()
> #20 {main}

The comment for that section of code is:

> // Add or alter the vertical tabs. Main content tab already added by tasty_backend_base module, just need to update it.

**Comment by frederickjh** [comment]
Well, I think that I can answer my own question, the dependency still seems to be there. After enabling the four tasty_backend modules: base, standard(with dependency on tasty_backend commented out), page and webform everything is not as tasty as I would like. The article and page content types add content have not changed from the standard install.

**Comment by jenitehan** [comment]
The Tasty Backend Standard module is only meant to be used with the Tasty Backend install profile, that's why the dependency on tasty_backend is there.  If you want to add TB functionality to an existing site you only need to install the [Tasty Backend Base module](https://github.com/jenitehan/tasty_backend_base).

**Comment by frederickjh** [comment]
Should the Tasty Backend Standard module make the existing content types tasty (add vertical tabs)?

**Comment by frederickjh** [comment]
I will answer my own question, no. 

Here is what I have figured out:
- Tasty Backend Standard sets up the Tasty Backend Article content type.  
- Tasty Backend Base does not setup  the following content types (machine names), **page**, **article**, **webform** to use the Tasty Backend. 

Lines 75 -80 from [tasty_backend_base.install](https://github.com/jenitehan/tasty_backend_base/blob/master/tasty_backend_base.install)

``` bash
      // Exclude certain content types that are handled by other tasty backend modules.
      $exclude = array(
        'article',
        'webform',
        'page',
      );
```
- There are separate modules to setup the Tasty Backend Basic Page and Tasty Backend Webform content types. 
- The article content type is included in the Tasty Backend Standard module which is dependant on the Tasty Backend installation profile. 

I am going to see if I can pull the Tasty Backend article content type code out of the Tasty Backend Standard module and make it stand on its own.

**Comment by frederickjh** [comment]
@jenitehan I created a new repository for a brand new [tasty_backend_article](https://github.com/meosch/tasty_backend_article).  In my testing this works to setup a Tasty Backend Article without the installation profile.

Feel free to fork it as is mostly code from tasty_backend_standard and the view from tasty_backend_base. I think I also got something from tasty_backend_page. 

I had to change the [hook_views_api](https://api.drupal.org/api/views/views.api.php/function/hook_views_api/7) in the **.module** file. You use **"version" => "3.0"**, but Drupal api for Drupal 6 and Drupal 7 uses **'api' => 3**. Maybe this is a different hook if it is in an installation profile vs. a module.

I also changed the permissions on the view to the same as is setup for the view included with tasty_backend_page.
